{
    'name': 'FM school',
    'version': '1.0',
    'author': 'Rohit',
    'license': 'LGPL-3',
    'maintainer': 'Aman Deep',
    'sequence': 0,
    'category': 'Education',
    'description': 'storing students information',
    'website': 'www.fmschool.org',
    'depends': ['base', 'mail'],
    'images': ['static/description/icon.png', 'static/description/activity.jpg', 'static/description/assembly.jpeg', 'static/description/bus.jpg', 'static/description/hh1.jpg', 'static/description/library.jpg', 'static/description/sports.jpg'],
    'summary': 'This is a school management System',
    'assets': {
        'web.assets_backend': [
            'school_management/static/src/**/*',
        ],
    },
    'data': [
        'security/ir.model.access.csv',
        'wizard/create_school_info_view.xml',
        'data/student_cron_template.xml',
        'views/snippets/records.xml',
        'views/snippets/employee_information.xml',
        'views/snippets/s_callup.xml',
        'views/snippets/s_student.xml',
        'views/snippets/snippets.xml',
        'reports/student_report.xml',
        'reports/inherit_qweb_template.xml',
        'data/student_mail_template.xml',
        'views/assets.xml',
        'views/emp.xml',
        'views/teacher_details.xml',
        'views/student_details.xml',
        'data/student_res_config_template.xml',
        'demo/demo_student.xml',
        'views/library_details.xml',
        'views/template.xml',
    ],


    'demo': ['demo/demo_student.xml',],

    'installable': True,
    'application': True,
    'active': True,
    'auto_install': False,
}
